// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proiect_Licenta.Data;

#nullable disable

namespace Proiect_Licenta.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260530185749_UltimaBaza")]
    partial class UltimaBaza
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Proiect_Licenta.Models.AdminLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerformedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PerformedByUserId");

                    b.ToTable("AdminLogs");
                });

            modelBuilder.Entity("Proiect_Licenta.Models.Aircraft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AirlineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId");

                    b.ToTable("Aircrafts");
                });

            modelBuilder.Entity("Proiect_Licenta.Models.Airline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("IATACode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("Name", "IATACode", "Country")
                        .IsUnique();

                    b.ToTable("Airlines");
                });

            modelBuilder.Entity("Proiect_Licenta.Models.Airport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("IATACode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ICAOCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Airports");
                });

            modelBuilder.Entity("Proiect_Licenta.Models.Badge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Badges");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000000"),
                            DateOfCreation = new DateTime(2026, 5, 30, 18, 57, 49, 333, DateTimeKind.Utc).AddTicks(4943),
                            Description = "You have created your account!",
                            Icon = "/images/welcome.png",
                            Name = "Welcome"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            DateOfCreation = new DateTime(2026, 5, 30, 18, 57, 49, 333, DateTimeKind.Utc).AddTicks(4957),
                            Description = "You posted for the first time",
                            Icon = "/images/post1.png",
                            Name = "First Post"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            DateOfCreation = new DateTime(2026, 5, 30, 18, 57, 49, 333, DateTimeKind.Utc).AddTicks(4960),
                            Description = "You made 5 posts",
                            Icon = "/images/post5.png",
                            Name = "Traveler"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000020"),
                            DateOfCreation = new DateTime(2026, 5, 30, 18, 57, 49, 333, DateTimeKind.Utc).AddTicks(4962),
                            Description = "You made 20 posts",
                            Icon = "/images/post20.png",
                            Name = "Explorer"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000050"),
                            DateOfCreation = new DateTime(2026, 5, 30, 18, 57, 49, 333, DateTimeKind.Utc).AddTicks(4965),
                            Description = "You made 50 posts",
                            Icon = "/images/post50.png",
                            Name = "Adventurer"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000100"),
                            DateOfCreation = new DateTime(2026, 5, 30, 18, 57, 49, 333, DateTimeKind.Utc).AddTicks(4967),
                            Description = "You made 100 posts",
                            Icon = "/images/post100.png",
                            Name = "Storyteller"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000250"),
                            DateOfCreation = new DateTime(2026, 5, 30, 18, 57, 49, 333, DateTimeKind.Utc).AddTicks(4969),
                            Description = "You made 250 posts",
                            Icon = "/images/post250.png",
                            Name = "Content Creator"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000500"),
                            DateOfCreation = new DateTime(2026, 5, 30, 18, 57, 49, 333, DateTimeKind.Utc).AddTicks(4982),
                            Description = "You made 500 posts",
                            Icon = "/images/post500.png",
                            Name = "Master Explorer"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000001000"),
                            DateOfCreation = new DateTime(2026, 5, 30, 18, 57, 49, 333, DateTimeKind.Utc).AddTicks(4983),
                            Description = "You made 1,000 posts",
                            Icon = "/images/post1000.png",
                            Name = "Legendary Poster"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            DateOfCreation = new DateTime(2026, 5, 30, 18, 57, 49, 333, DateTimeKind.Utc).AddTicks(4985),
                            Description = "Reached level 5",
                            Icon = "/images/level5.png",
                            Name = "Getting Started"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000010"),
                            DateOfCreation = new DateTime(2026, 5, 30, 18, 57, 49, 333, DateTimeKind.Utc).AddTicks(4987),
                            Description = "Reached level 10",
                            Icon = "/images/level10.png",
                            Name = "Rising Star"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000020"),
                            DateOfCreation = new DateTime(2026, 5, 30, 18, 57, 49, 333, DateTimeKind.Utc).AddTicks(4989),
                            Description = "Reached level 20",
                            Icon = "/images/level20.png",
                            Name = "Challenger"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000050"),
                            DateOfCreation = new DateTime(2026, 5, 30, 18, 57, 49, 333, DateTimeKind.Utc).AddTicks(4991),
                            Description = "Reached level 50",
                            Icon = "/images/level50.png",
                            Name = "Veteran Explorer"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000100"),
                            DateOfCreation = new DateTime(2026, 5, 30, 18, 57, 49, 333, DateTimeKind.Utc).AddTicks(4992),
                            Description = "Reached level 100",
                            Icon = "/images/level100.png",
                            Name = "Legend of InfinityFit"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            DateOfCreation = new DateTime(2026, 5, 30, 18, 57, 49, 333, DateTimeKind.Utc).AddTicks(4994),
                            Description = "Gave your first like",
                            Icon = "/images/like1.png",
                            Name = "First Love"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000010"),
                            DateOfCreation = new DateTime(2026, 5, 30, 18, 57, 49, 333, DateTimeKind.Utc).AddTicks(4999),
                            Description = "Gave 10 likes",
                            Icon = "/images/like10.png",
                            Name = "Supporter"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000050"),
                            DateOfCreation = new DateTime(2026, 5, 30, 18, 57, 49, 333, DateTimeKind.Utc).AddTicks(5001),
                            Description = "Gave 50 likes",
                            Icon = "/images/like50.png",
                            Name = "Positive Vibes"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000100"),
                            DateOfCreation = new DateTime(2026, 5, 30, 18, 57, 49, 333, DateTimeKind.Utc).AddTicks(5002),
                            Description = "Gave 100 likes",
                            Icon = "/images/like100.png",
                            Name = "Community Booster"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000500"),
                            DateOfCreation = new DateTime(2026, 5, 30, 18, 57, 49, 333, DateTimeKind.Utc).AddTicks(5004),
                            Description = "Gave 500 likes",
                            Icon = "/images/like500.png",
                            Name = "Influencer"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000001000"),
                            DateOfCreation = new DateTime(2026, 5, 30, 18, 57, 49, 333, DateTimeKind.Utc).AddTicks(5006),
                            Description = "Gave 1,000 likes",
                            Icon = "/images/like1000.png",
                            Name = "Social Machine"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000005000"),
                            DateOfCreation = new DateTime(2026, 5, 30, 18, 57, 49, 333, DateTimeKind.Utc).AddTicks(5008),
                            Description = "Gave 5,000 likes",
                            Icon = "/images/like5000.png",
                            Name = "Infinity Reactor"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            DateOfCreation = new DateTime(2026, 5, 30, 18, 57, 49, 333, DateTimeKind.Utc).AddTicks(5010),
                            Description = "Posted your first comment",
                            Icon = "/images/comment1.png",
                            Name = "First Words"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000005"),
                            DateOfCreation = new DateTime(2026, 5, 30, 18, 57, 49, 333, DateTimeKind.Utc).AddTicks(5012),
                            Description = "Posted 5 comments",
                            Icon = "/images/comment5.png",
                            Name = "Conversationalist"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000015"),
                            DateOfCreation = new DateTime(2026, 5, 30, 18, 57, 49, 333, DateTimeKind.Utc).AddTicks(5015),
                            Description = "Posted 15 comments",
                            Icon = "/images/comment15.png",
                            Name = "Active Voice"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000050"),
                            DateOfCreation = new DateTime(2026, 5, 30, 18, 57, 49, 333, DateTimeKind.Utc).AddTicks(5017),
                            Description = "Posted 50 comments",
                            Icon = "/images/comment50.png",
                            Name = "Discussion Leader"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000100"),
                            DateOfCreation = new DateTime(2026, 5, 30, 18, 57, 49, 333, DateTimeKind.Utc).AddTicks(5018),
                            Description = "Posted 100 comments",
                            Icon = "/images/comment100.png",
                            Name = "Community Speaker"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000250"),
                            DateOfCreation = new DateTime(2026, 5, 30, 18, 57, 49, 333, DateTimeKind.Utc).AddTicks(5020),
                            Description = "Posted 250 comments",
                            Icon = "/images/comment250.png",
                            Name = "Debater Pro"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000500"),
                            DateOfCreation = new DateTime(2026, 5, 30, 18, 57, 49, 333, DateTimeKind.Utc).AddTicks(5022),
                            Description = "Posted 500 comments",
                            Icon = "/images/comment500.png",
                            Name = "Social Anchor"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000001000"),
                            DateOfCreation = new DateTime(2026, 5, 30, 18, 57, 49, 333, DateTimeKind.Utc).AddTicks(5024),
                            Description = "Posted 1,000 comments",
                            Icon = "/images/comment1000.png",
                            Name = "Voice of Infinity"
                        });
                });

            modelBuilder.Entity("Proiect_Licenta.Models.BaggageItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int?>("WeightKg")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("baggageItems");
                });

            modelBuilder.Entity("Proiect_Licenta.Models.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FlightId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Proiect_Licenta.Models.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Proiect_Licenta.Models.Flight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AircraftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AirlineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArrivalAirportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DepartureAirportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.HasIndex("AirlineId");

                    b.HasIndex("ArrivalAirportId");

                    b.HasIndex("DepartureAirportId");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("Proiect_Licenta.Models.FlightSeat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FlightId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SeatId");

                    b.HasIndex("TicketId")
                        .IsUnique()
                        .HasFilter("[TicketId] IS NOT NULL");

                    b.HasIndex("FlightId", "SeatId")
                        .IsUnique();

                    b.ToTable("FlightSeats");
                });

            modelBuilder.Entity("Proiect_Licenta.Models.Like", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId", "PostId")
                        .IsUnique();

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("Proiect_Licenta.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SenderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("SenderId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Proiect_Licenta.Models.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Proiect_Licenta.Models.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CommentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FlightId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReporterId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ReviewedByAdminId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("FlightId");

                    b.HasIndex("PostId");

                    b.HasIndex("ReporterId");

                    b.HasIndex("ReviewedByAdminId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Proiect_Licenta.Models.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SeatSectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TravelClass")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeatSectionId");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("Proiect_Licenta.Models.SeatSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AircraftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<int>("EndRow")
                        .HasColumnType("int");

                    b.Property<string>("Layout")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StartRow")
                        .HasColumnType("int");

                    b.Property<int>("TravelClass")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.ToTable("SeatSections");
                });

            modelBuilder.Entity("Proiect_Licenta.Models.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TravelClass")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Proiect_Licenta.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("AirlineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("FlightsBooked")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompany")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLevelUp")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Level")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TotalPoints")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Proiect_Licenta.Models.UserBadge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BadgeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BadgeId");

                    b.HasIndex("UserId");

                    b.ToTable("UserBadges");
                });

            modelBuilder.Entity("Proiect_Licenta.Models.Voucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Vouchers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Proiect_Licenta.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Proiect_Licenta.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proiect_Licenta.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Proiect_Licenta.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Proiect_Licenta.Models.AdminLog", b =>
                {
                    b.HasOne("Proiect_Licenta.Models.User", "PerformedByUser")
                        .WithMany()
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PerformedByUser");
                });

            modelBuilder.Entity("Proiect_Licenta.Models.Aircraft", b =>
                {
                    b.HasOne("Proiect_Licenta.Models.Airline", "Airline")
                        .WithMany("Aircraft")
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airline");
                });

            modelBuilder.Entity("Proiect_Licenta.Models.Airline", b =>
                {
                    b.HasOne("Proiect_Licenta.Models.User", "User")
                        .WithOne("Airline")
                        .HasForeignKey("Proiect_Licenta.Models.Airline", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Proiect_Licenta.Models.BaggageItem", b =>
                {
                    b.HasOne("Proiect_Licenta.Models.Ticket", "Ticket")
                        .WithMany("BaggageItems")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Proiect_Licenta.Models.Booking", b =>
                {
                    b.HasOne("Proiect_Licenta.Models.Flight", "Flight")
                        .WithMany("Bookings")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proiect_Licenta.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Proiect_Licenta.Models.Comment", b =>
                {
                    b.HasOne("Proiect_Licenta.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Proiect_Licenta.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Proiect_Licenta.Models.Flight", b =>
                {
                    b.HasOne("Proiect_Licenta.Models.Aircraft", "Aircraft")
                        .WithMany("Flights")
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proiect_Licenta.Models.Airline", "Airline")
                        .WithMany("Flights")
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proiect_Licenta.Models.Airport", "ArrivalAirport")
                        .WithMany("ArrivingFlights")
                        .HasForeignKey("ArrivalAirportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proiect_Licenta.Models.Airport", "DepartureAirport")
                        .WithMany("DepartingFlights")
                        .HasForeignKey("DepartureAirportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aircraft");

                    b.Navigation("Airline");

                    b.Navigation("ArrivalAirport");

                    b.Navigation("DepartureAirport");
                });

            modelBuilder.Entity("Proiect_Licenta.Models.FlightSeat", b =>
                {
                    b.HasOne("Proiect_Licenta.Models.Flight", "Flight")
                        .WithMany("FlightSeats")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proiect_Licenta.Models.Seat", "Seat")
                        .WithMany("FlightSeats")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proiect_Licenta.Models.Ticket", "Ticket")
                        .WithOne()
                        .HasForeignKey("Proiect_Licenta.Models.FlightSeat", "TicketId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Flight");

                    b.Navigation("Seat");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Proiect_Licenta.Models.Like", b =>
                {
                    b.HasOne("Proiect_Licenta.Models.Post", "Post")
                        .WithMany("Likes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Proiect_Licenta.Models.User", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Proiect_Licenta.Models.Notification", b =>
                {
                    b.HasOne("Proiect_Licenta.Models.Post", "Post")
                        .WithMany("Notifications")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Proiect_Licenta.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Proiect_Licenta.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Sender");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Proiect_Licenta.Models.Post", b =>
                {
                    b.HasOne("Proiect_Licenta.Models.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Proiect_Licenta.Models.Report", b =>
                {
                    b.HasOne("Proiect_Licenta.Models.Comment", "Comment")
                        .WithMany("Reports")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Proiect_Licenta.Models.Flight", "Flight")
                        .WithMany("Reports")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Proiect_Licenta.Models.Post", "Post")
                        .WithMany("Reports")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Proiect_Licenta.Models.User", "Reporter")
                        .WithMany("Reports")
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proiect_Licenta.Models.User", "ReviewedByAdmin")
                        .WithMany()
                        .HasForeignKey("ReviewedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Comment");

                    b.Navigation("Flight");

                    b.Navigation("Post");

                    b.Navigation("Reporter");

                    b.Navigation("ReviewedByAdmin");
                });

            modelBuilder.Entity("Proiect_Licenta.Models.Seat", b =>
                {
                    b.HasOne("Proiect_Licenta.Models.SeatSection", "SeatSection")
                        .WithMany("Seats")
                        .HasForeignKey("SeatSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SeatSection");
                });

            modelBuilder.Entity("Proiect_Licenta.Models.SeatSection", b =>
                {
                    b.HasOne("Proiect_Licenta.Models.Aircraft", "Aircraft")
                        .WithMany("SeatSections")
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aircraft");
                });

            modelBuilder.Entity("Proiect_Licenta.Models.Ticket", b =>
                {
                    b.HasOne("Proiect_Licenta.Models.Booking", "Booking")
                        .WithMany("Tickets")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Proiect_Licenta.Models.UserBadge", b =>
                {
                    b.HasOne("Proiect_Licenta.Models.Badge", "Badge")
                        .WithMany("UserBadges")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proiect_Licenta.Models.User", "User")
                        .WithMany("UserBadges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Proiect_Licenta.Models.Voucher", b =>
                {
                    b.HasOne("Proiect_Licenta.Models.User", "User")
                        .WithMany("Vouchers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Proiect_Licenta.Models.Aircraft", b =>
                {
                    b.Navigation("Flights");

                    b.Navigation("SeatSections");
                });

            modelBuilder.Entity("Proiect_Licenta.Models.Airline", b =>
                {
                    b.Navigation("Aircraft");

                    b.Navigation("Flights");
                });

            modelBuilder.Entity("Proiect_Licenta.Models.Airport", b =>
                {
                    b.Navigation("ArrivingFlights");

                    b.Navigation("DepartingFlights");
                });

            modelBuilder.Entity("Proiect_Licenta.Models.Badge", b =>
                {
                    b.Navigation("UserBadges");
                });

            modelBuilder.Entity("Proiect_Licenta.Models.Booking", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Proiect_Licenta.Models.Comment", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("Proiect_Licenta.Models.Flight", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("FlightSeats");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("Proiect_Licenta.Models.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likes");

                    b.Navigation("Notifications");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("Proiect_Licenta.Models.Seat", b =>
                {
                    b.Navigation("FlightSeats");
                });

            modelBuilder.Entity("Proiect_Licenta.Models.SeatSection", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("Proiect_Licenta.Models.Ticket", b =>
                {
                    b.Navigation("BaggageItems");
                });

            modelBuilder.Entity("Proiect_Licenta.Models.User", b =>
                {
                    b.Navigation("Airline");

                    b.Navigation("Bookings");

                    b.Navigation("Comments");

                    b.Navigation("Likes");

                    b.Navigation("Notifications");

                    b.Navigation("Posts");

                    b.Navigation("Reports");

                    b.Navigation("UserBadges");

                    b.Navigation("Vouchers");
                });
#pragma warning restore 612, 618
        }
    }
}
